### PR TITLE
Updates from mspsim/mspsim

### PR DESCRIPTION
**Pull request by nfi**
This pull request contains the latest fixes and improvements from the MSPSim GitHub repository including a DCO clock speed fix to make Z1 nodes run at the correct speed in Cooja.

This time I did a rebase of mspsim/mspsim master on top of contiki-os/mspsim fork but is this the right way to submit updates for MSPSim in Contiki OS in the future?

### CODE REVIEW

**Comment by simonduq** [comment]
Great to get both repos synced up. I have tried this DCO clock fix before and it works nicely (without it, z1 runs twice as slow as it should).
Also, I have tested Contiki's Travis against it, it's all green: https://github.com/simonduq/contiki/pull/27
:+1:

**Comment by simonduq** [comment]
@adamdunkels @fros4943 would you consider merging this?

**Comment by adamdunkels** [comment]
:+1: great that you ran it through travis @simonduq !

**Comment by simonduq** [comment]
Thanks!

**Pull request merged**
